settings:
  poll_delay: 5 # seconds
mastodon:
  api:
    # use the base URL of your mastodon server e.g. https://botsin.space
    base_url: "https://botsin.space"
    access_token: null
twitter:
  api:
    base_url: "https://api.twitter.com"
    bearer_token: null
  following:
    lists:
      # use twitter list IDs
      # - "1275634424898629632"
    users:
      # use twitter user IDs or usernames prefixed by @
      # - "@mejszin"